# Generated by Django 6.0.5 on 2026-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='sample_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
