# Generated by Django 6.0.5 on 2026-06-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0002_audiofile_duration_audiofile_sample_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='fingerprint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
