# Generated by Django 6.0.5 on 2026-06-02 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0003_audiofile_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_audio', to='forensic.audiofile')),
                ('suspect_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_audio', to='forensic.audiofile')),
            ],
        ),
    ]
