# Generated by Django 6.0.5 on 2026-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0004_verificationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrecord',
            name='similarity_score',
            field=models.FloatField(default=0),
        ),
    ]
