# Generated by Django 6.0.5 on 2026-06-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0005_verificationrecord_similarity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='mfcc_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
