# Generated by Django 6.0.5 on 2026-06-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0006_audiofile_mfcc_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='watermark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
