# Generated by Django 6.0.5 on 2026-06-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0007_audiofile_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrecord',
            name='tamper_status',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
