# Generated by Django 6.0.5 on 2026-06-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0008_verificationrecord_tamper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrecord',
            name='tampered_segment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
