# Generated by Django 6.0.5 on 2026-06-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0010_fix_related_names_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='verificationrecord',
            options={'ordering': ['-created_at']},
        ),
    ]
